### ISSUE TITLE
F create error

### ISSUE THREAD

**Issue by tehrenderr** [MarkehMe/FactionsFramework#10]
http://pastebin.com/eQuxk1wa

**Comment by MarkehMe** [comment]
Are you still using a modified version of Factions?

**Comment by tehrenderr** [comment]
Yes it's the same modified factions I sent you in previous threads, I'm still running 2.7.5 factions and massivecore.

**Comment by MarkehMe** [comment]
Although there wasn't a layer for 2.7 (i've added it now) it seems that your server is picking up 2.8.6.

The best way to solve this is for your plugin developer to use a publicly maintained Factions version and use the API provided. However you can also [use the new override methods](https://github.com/MarkehMe/FactionsFramework/commit/eae4354012cb85e36ac9714d9dc7249f6595ae77) to set these yourself - this is in [this development built](https://app.wercker.com/#RedstoneOre/FactionsFramework/build/574ba7dfae1a1b664802ef44?step=574ba7e3a2f66a00019974ac).

Do you really require using a custom version of Factions? Can your features not be added by using an API? I unfortunately can not just add support for individual custom builds of factions, that would just become tiresome.
