### ISSUE TITLE
Faction create error

### ISSUE THREAD

**Issue by tehrenderr** [MarkehMe/FactionsFramework#14]
I keep getting this error using factions framework

http://pastebin.com/PGk1Y9Rt

**Comment by MarkehMe** [comment]
Please supply more information. I am unable to help you if you do not supply information that describes your environment. 

* Server Version
* Factions Version
* MassiveCore Version (if required)

**Comment by tehrenderr** [comment]
I am using 1.8.8 paperspigot and factions and massivecore v2.7.5

**Comment by MarkehMe** [comment]
Are you still using a custom build of Factions and MassiveCore?

**Comment by MarkehMe** [comment]
As I have said before custom builds are not supported. There is something different that is triggering FactionsFramework to think it is a different version.

Your developer will need to override the events layer:

```java
EventsLayer.overrideEventsLayer(
    (Handler) Class.forName("me.markeh.factionsframework.layer.layer_2_7.Events_2_7").newInstance()
);
```

and the same for command manager as it is different too:

```java
FactionsCommandManager.overrideEventsLayer(
    (Handler) Class.forName("me.markeh.factionsframework.layer.layer_2_7.CommandManager_2_7").newInstance();
);
```

**Please** be careful with custom builds and always consider making add-ons to preserve compatibility. These can cause a lot of issues.
