### ISSUE TITLE
/f claim error

### ISSUE THREAD

**Issue by TheKillHDmc** [MarkehMe/FactionsFramework#28]
Hello,

Here is my error : https://pastebin.com/paNjg6eZ

I use factionsuuid : Factions v1.6.9.5-U0.1.21

Server version : git-TacoSpigot-"c98afce0" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

Thanks !

**Comment by markhughes** [comment]
Sorry, FactionsUUID API is broken at the moment!

See #24
  :)
