### ISSUE TITLE
Faction Prefixes

### ISSUE THREAD

**Issue by Morello24** [MarkehMe/FactionsFramework#6]
Hello, would you be interested in porting the factionsuuid prefixes to the massive  factions 2.8.7 using your api?
Plugin: https://github.com/drtshock/Factions
Everything is on the package "scoreboard". 
With prefixes I mean the color in the name above the head (This change depending of your relation-ship with other players).

**Comment by MarkehMe** [comment]
Faction Scoreboard features are nice - I agree, they should be available to everyone. I will port this into a new plugin 😃

**Comment by Morello24** [comment]
Thank you so much :) I'm very happy now.

**Comment by Morello24** [comment]
Do you know when you will finish this? I'm just wondering because I'll launch my server soon.

**Comment by MarkehMe** [comment]
It isn't too complicated to make, it's just I have other work on. But it's on my list to do.

If you find my plugins helpful, feel free to contribute (even a small $3 amount) to my [patreon campaign](https://www.patreon.com/markehme).

**Comment by Morello24** [comment]
Okay :)

**Comment by MarkehMe** [comment]
Closing this as its not apart of FactionsFramework, hopefully will be picked up somewhere else. :)
