### ISSUE TITLE
Required argument being ignored in 2.7.5

### ISSUE THREAD

**Issue by MarkehMe** [MarkehMe/FactionsFramework#7]
This is a followup of https://github.com/MarkehMe/FactionsWarps/issues/7 by @tehrenderr

It appears that the required argument is being ignored. This can be bypassed by allowing overflows, however a fix needs to be implemented.

**Comment by tehrenderr** [comment]
How do I allow overflows to bypass the issue? I'm not sure what that entails.

**Comment by MarkehMe** [comment]
You don't need to do anything, just grab the next version

**Comment by tehrenderr** [comment]
Do you know when you will be able to release the next version of FactionWarps? Players are unable to delete warps.

**Comment by MarkehMe** [comment]
Please try this and let me know:

[FactionsWarps.jar.zip](https://github.com/MarkehMe/FactionsFramework/files/276757/FactionsWarps.jar.zip)
