### ISSUE TITLE
Unable to set FactionWarps

### ISSUE THREAD

**Issue by VerumUK** [MarkehMe/FactionsFramework#9]
Hey there I get the following error in console when an Officer player attempts to set a faction warp, I am unsure if this is a frameworks issue or your factionwarps plugin but by error in console I'm going to assume frameworks.

http://pastebin.com/8eMM4aRL

Side note: framework: 1.1.2 factionwarps: 1.1.1

**Comment by MarkehMe** [comment]
I believe this is the same issue as this one: https://github.com/MarkehMe/FactionsWarps/issues/10

It's when we check the leader for permission, for now it's best just to disable officers to set it and only allow leaders. I'll fix this in the next release 😄
